In [1]:
from mxnet import autograd,nd

In [2]:
x = nd.arange(4).reshape((4,1))
x


[[0.]
 [1.]
 [2.]
 [3.]]
<NDArray 4x1 @cpu(0)>

In [3]:
x = nd.arange(4).reshape((4,1))
x


[[0.]
 [1.]
 [2.]
 [3.]]
<NDArray 4x1 @cpu(0)>

In [4]:
x.attach_grad()

### with 语法

"""
with 语句实质是上下文管理。
1、上下文管理协议。包含方法__enter__() 和 __exit__()，支持该协议对象要实现这两个方法。
2、上下文管理器，定义执行with语句时要建立的运行时上下文，负责执行with语句块上下文中的进入与退出操作。
3、进入上下文的时候执行__enter__方法，如果设置as var语句，var变量接受__enter__()方法返回值。
4、如果运行时发生了异常，就退出上下文管理器。调用管理器__exit__方法。
"""

In [6]:
with autograd.record():
    y = 2 * nd.dot(x.T,x)

In [7]:
y.backward()

### assert 语句

https://www.runoob.com/python3/python3-assert.html

In [11]:
assert (x.grad-4*x).norm().asscalar() ==0
x.grad
 
       #asscaler ：是将向量 转成标量
       #assert 是断言


[[ 0.]
 [ 4.]
 [ 8.]
 [12.]]
<NDArray 4x1 @cpu(0)>

In [ ]:
#norm 是L2 (x1^2 + x2^2)^0.5

In [34]:
def f(a):
    b = a*2

    while b.norm().asscalar()<1000:
        b = b*2

    if b.sum().asscalar() >0:
        c =b
    else:
        c = 100 *b
        
    return c 

In [58]:
a = nd.array([[2],[3]])
a


[[2.]
 [3.]]
<NDArray 2x1 @cpu(0)>

In [59]:
a.attach_grad()
with autograd.record():
    c = f(a)
c.backward()

In [61]:
c


[[1024.]
 [1536.]]
<NDArray 2x1 @cpu(0)>

In [60]:
a.grad


[[512.]
 [512.]]
<NDArray 2x1 @cpu(0)>

In [49]:
c/a


[204800.]
<NDArray 1 @cpu(0)>

In [37]:
a.grad == c/a
  #ture是1


[1.]
<NDArray 1 @cpu(0)>

In [50]:
a = nd.random.normal(shape = (4,1))
a


[[-2.3556297]
 [ 0.5414402]
 [ 2.6785066]
 [ 1.2546344]]
<NDArray 4x1 @cpu(0)>

In [51]:
a.attach_grad()
with autograd.record():
    c = f(a)
c.backward()

In [52]:
c


[[-1206.0824 ]
 [  277.21738]
 [ 1371.3954 ]
 [  642.3728 ]]
<NDArray 4x1 @cpu(0)>

In [55]:
c/a


[[512.]
 [512.]
 [512.]
 [512.]]
<NDArray 4x1 @cpu(0)>

In [53]:
a.grad


[[512.]
 [512.]
 [512.]
 [512.]]
<NDArray 4x1 @cpu(0)>

In [54]:
a.grad == c/a


[[1.]
 [1.]
 [1.]
 [1.]]
<NDArray 4x1 @cpu(0)>

## 练习

#### 在本节对控制流求梯度的例子中，把变量a改成一个随机向量或矩阵。此时计算结果c不再 是标量，运行结果将有何变化?该如何分析该结果?

1.a是矩阵： c自然就是矩阵，但是因为a是点乘


  ?????为啥都是512啊？？？？