# 数据操作

建立ndarray

In [1]:
from mxnet import nd
x = nd.arange(12)

In [2]:
x


[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
<NDArray 12 @cpu(0)>

In [3]:
x.shape

(12,)

In [4]:
x.reshape(3,4)


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

In [5]:
x1 = x.reshape(3,4)

In [6]:
x1


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

In [7]:
nd.zeros((2,3,4))
  #这个地方是说 2个 3行4列的array


[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
<NDArray 2x3x4 @cpu(0)>

In [8]:
nd.ones((3,4))


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<NDArray 3x4 @cpu(0)>

In [9]:
y = nd.array([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
y


[[2. 1. 4. 3.]
 [1. 2. 3. 4.]
 [4. 3. 2. 1.]]
<NDArray 3x4 @cpu(0)>

In [11]:
nd.random.normal(0,1,shape=(3,4))
  #随机的地方是 3行4列


[[ 1.1630787   0.4838046   0.29956347  0.15302546]
 [-1.1688148   1.5580711  -0.5459446  -2.3556297 ]
 [ 0.5414402   2.6785066   1.2546344  -0.54877394]]
<NDArray 3x4 @cpu(0)>

运算

In [13]:
 x1 +y


[[ 2.  2.  6.  6.]
 [ 5.  7.  9. 11.]
 [12. 12. 12. 12.]]
<NDArray 3x4 @cpu(0)>

In [14]:
x1*y  
   #这里是按照元素的位置相乘
   #直接使用加减乘除都是对的位置


[[ 0.  1.  8.  9.]
 [ 4. 10. 18. 28.]
 [32. 27. 20. 11.]]
<NDArray 3x4 @cpu(0)>

In [15]:
x1/y


[[ 0.    1.    0.5   1.  ]
 [ 4.    2.5   2.    1.75]
 [ 2.    3.    5.   11.  ]]
<NDArray 3x4 @cpu(0)>

In [16]:
y.exp()


[[ 7.389056   2.7182817 54.59815   20.085537 ]
 [ 2.7182817  7.389056  20.085537  54.59815  ]
 [54.59815   20.085537   7.389056   2.7182817]]
<NDArray 3x4 @cpu(0)>

In [21]:
nd.dot(x1,y.T)
  #ND.dot是矩阵的乘法


[[ 18.  20.  10.]
 [ 58.  60.  50.]
 [ 98. 100.  90.]]
<NDArray 3x3 @cpu(0)>

In [24]:
nd.concat(x1,y,dim=0)
   #3*4这个表达中，0就是行因此 dim=0就是链接行


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [ 2.  1.  4.  3.]
 [ 1.  2.  3.  4.]
 [ 4.  3.  2.  1.]]
<NDArray 6x4 @cpu(0)>

In [25]:
nd.concat(x1,y,dim=1)


[[ 0.  1.  2.  3.  2.  1.  4.  3.]
 [ 4.  5.  6.  7.  1.  2.  3.  4.]
 [ 8.  9. 10. 11.  4.  3.  2.  1.]]
<NDArray 3x8 @cpu(0)>

In [26]:
x1==y


[[0. 1. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
<NDArray 3x4 @cpu(0)>

In [27]:
x1.sum()


[66.]
<NDArray 1 @cpu(0)>

In [29]:
x1.norm().asscalar()

22.494442

boardcasting 

本质是 复制去粘贴，那么就要求列或者行是整数倍


是以1为基础
[3,2]+ [6,2] 这种都是不可以的

In [30]:
a = nd.arange(3).reshape((3, 1))
b= nd.arange(2).reshape((1, 2))

In [31]:
a


[[0.]
 [1.]
 [2.]]
<NDArray 3x1 @cpu(0)>

In [32]:
b


[[0. 1.]]
<NDArray 1x2 @cpu(0)>

In [33]:
a+b
   #这里是 a来复制它自己


[[0. 1.]
 [1. 2.]
 [2. 3.]]
<NDArray 3x2 @cpu(0)>

In [48]:
c = nd.arange(6).reshape((3, 2))
c


[[0. 1.]
 [2. 3.]
 [4. 5.]]
<NDArray 3x2 @cpu(0)>

In [54]:
a+c


[[0. 1.]
 [3. 4.]
 [6. 7.]]
<NDArray 3x2 @cpu(0)>

In [56]:
b+c


[[0. 2.]
 [2. 4.]
 [4. 6.]]
<NDArray 3x2 @cpu(0)>

In [66]:
d= nd.arange(24).reshape(6,2)
d


[[ 0.  1.]
 [ 2.  3.]
 [ 4.  5.]
 [ 6.  7.]
 [ 8.  9.]
 [10. 11.]]
<NDArray 6x2 @cpu(0)>

索引

In [37]:
x1[1:3]


[[ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 2x4 @cpu(0)>

In [39]:
x1


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

In [38]:
x1[1,2]


[6.]
<NDArray 1 @cpu(0)>

In [40]:
x1[1:2,:]=12
  #这里是取的 2-1 行

In [41]:
x1


[[ 0.  1.  2.  3.]
 [12. 12. 12. 12.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

mnxt 在变量的存储上面：
    
    
    相同的变量名字是用的同一个地址，这样节约内存。
    因此对同一个变量名字的操作是替换

In [42]:
import numpy as np

In [44]:
p = np.ones((2, 3))
d = nd.array(p)

In [45]:
d


[[1. 1. 1.]
 [1. 1. 1.]]
<NDArray 2x3 @cpu(0)>

In [46]:
d.asnumpy()

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

自动求梯度

In [68]:
from mxnet import autograd,nd

In [69]:
x = nd.arange(4).reshape((4,1))

In [70]:
x


[[0.]
 [1.]
 [2.]
 [3.]]
<NDArray 4x1 @cpu(0)>

In [72]:
#attach_grad是存储梯度需要的内容
x.attach_grad()

In [73]:
#目标函数
with autograd.record():
    y = 2*nd.dot(x.T,x)
  #这里需要y是一个标量，如果不是需要变成标量

In [74]:
y.backward()

In [75]:
assert (x.grad - 4*x).norm().asscalar()==0

In [76]:
x.grad
  #这里是一个4x


[[ 0.]
 [ 4.]
 [ 8.]
 [12.]]
<NDArray 4x1 @cpu(0)>